@domain=http://127.0.0.1:8080/api/v1


GET {{domain}}/users?limit=10 HTTP/1.1
Accept: application/json

###

GET {{domain}}/users/20 HTTP/1.1
Accept: application/json

###

GET {{domain}}/products HTTP/1.1
Accept: application/json

###

GET {{domain}}/products/1 HTTP/1.1
Accept: application/json


